[package]
name = "paynal"
version = "0.1.0"
edition = "2021"
authors = ["Carlos Torres <j.carlos.torres@me.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.40.0", features = ["full"] }
